# Generated by Django 4.2.13 on 2024-05-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_profile_jmcjrv', upload_to='', verbose_name='images/'),
        ),
    ]
